import type { ProjectTemplate } from '@/types';

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'tmpl-software',
    name: 'Software Development',
    description: 'Standard agile workflow for software projects with backlog, sprints, and deployment stages.',
    icon: '💻',
    color: '#4A90D9',
    columns: [
      { name: 'Backlog', color: '#6E6E68', order: 0 },
      { name: 'To Do', color: '#94948C', order: 1 },
      { name: 'In Progress', color: '#B08D57', order: 2 },
      { name: 'In Review', color: '#4A90D9', order: 3 },
      { name: 'Done', color: '#4AAD7A', order: 4 },
    ],
    tasks: [
      { title: 'Project Setup & Architecture', priority: 'high', status: 'Backlog', labels: [] },
      { title: 'Design System & UI Components', priority: 'high', status: 'Backlog', labels: [] },
      { title: 'Authentication Module', priority: 'urgent', status: 'Backlog', labels: [] },
      { title: 'Core API Integration', priority: 'high', status: 'Backlog', labels: [] },
      { title: 'Unit Tests', priority: 'medium', status: 'Backlog', labels: [] },
      { title: 'Performance Optimization', priority: 'low', status: 'Backlog', labels: [] },
      { title: 'Deployment Pipeline', priority: 'medium', status: 'Backlog', labels: [] },
    ],
  },
  {
    id: 'tmpl-marketing',
    name: 'Marketing Campaign',
    description: 'End-to-end campaign management from strategy to execution and reporting.',
    icon: '📢',
    color: '#D96B4A',
    columns: [
      { name: 'Ideas', color: '#7C6FAF', order: 0 },
      { name: 'Planning', color: '#B08D57', order: 1 },
      { name: 'In Progress', color: '#4A90D9', order: 2 },
      { name: 'Review', color: '#ED8936', order: 3 },
      { name: 'Published', color: '#4AAD7A', order: 4 },
    ],
    tasks: [
      { title: 'Campaign Strategy & Goals', priority: 'high', status: 'Ideas', labels: [] },
      { title: 'Audience Research', priority: 'high', status: 'Planning', labels: [] },
      { title: 'Content Calendar', priority: 'medium', status: 'Planning', labels: [] },
      { title: 'Social Media Assets', priority: 'medium', status: 'Ideas', labels: [] },
      { title: 'Email Campaign', priority: 'high', status: 'Ideas', labels: [] },
      { title: 'Landing Page Copy', priority: 'medium', status: 'Ideas', labels: [] },
      { title: 'Performance Report', priority: 'low', status: 'Ideas', labels: [] },
    ],
  },
  {
    id: 'tmpl-design',
    name: 'Design Project',
    description: 'Creative project workflow from brief to final deliverable.',
    icon: '🎨',
    color: '#7C6FAF',
    columns: [
      { name: 'Brief', color: '#6E6E68', order: 0 },
      { name: 'Research', color: '#94948C', order: 1 },
      { name: 'Design', color: '#7C6FAF', order: 2 },
      { name: 'Feedback', color: '#D96B4A', order: 3 },
      { name: 'Delivered', color: '#4AAD7A', order: 4 },
    ],
    tasks: [
      { title: 'Creative Brief Review', priority: 'high', status: 'Brief', labels: [] },
      { title: 'Competitor Analysis', priority: 'medium', status: 'Research', labels: [] },
      { title: 'Moodboard & Inspiration', priority: 'low', status: 'Research', labels: [] },
      { title: 'Initial Concepts', priority: 'high', status: 'Design', labels: [] },
      { title: 'Wireframes', priority: 'high', status: 'Design', labels: [] },
      { title: 'High-Fidelity Mockups', priority: 'high', status: 'Design', labels: [] },
      { title: 'Client Presentation', priority: 'medium', status: 'Brief', labels: [] },
    ],
  },
  {
    id: 'tmpl-product',
    name: 'Product Launch',
    description: 'Coordinate all activities needed for a successful product launch.',
    icon: '🚀',
    color: '#4AAD7A',
    columns: [
      { name: 'Pre-Launch', color: '#7C6FAF', order: 0 },
      { name: 'In Progress', color: '#B08D57', order: 1 },
      { name: 'Review', color: '#4A90D9', order: 2 },
      { name: 'Ready', color: '#ED8936', order: 3 },
      { name: 'Launched', color: '#4AAD7A', order: 4 },
    ],
    tasks: [
      { title: 'Product Requirements Document', priority: 'urgent', status: 'Pre-Launch', labels: [] },
      { title: 'Beta Testing Program', priority: 'high', status: 'Pre-Launch', labels: [] },
      { title: 'Press Kit Preparation', priority: 'medium', status: 'Pre-Launch', labels: [] },
      { title: 'Pricing Strategy', priority: 'high', status: 'Pre-Launch', labels: [] },
      { title: 'Launch Event Planning', priority: 'medium', status: 'Pre-Launch', labels: [] },
      { title: 'Post-Launch Monitoring', priority: 'high', status: 'Pre-Launch', labels: [] },
    ],
  },
  {
    id: 'tmpl-blank',
    name: 'Blank Project',
    description: 'Start from scratch with a simple To Do → In Progress → Done workflow.',
    icon: '📋',
    color: '#B08D57',
    columns: [
      { name: 'To Do', color: '#6E6E68', order: 0 },
      { name: 'In Progress', color: '#B08D57', order: 1 },
      { name: 'Done', color: '#4AAD7A', order: 2 },
    ],
    tasks: [],
  },
];
